### ISSUE TITLE
Switch publicdomainmap.org DNS to use GitHub pages

### ISSUE THREAD

**Issue by quincylvania** [publicdomainmap/publicdomainmap.github.io#5]
Since this is a Jekyll site, we can use GitHub pages for free hosting. The site is already live at https://publicdomainmap.github.io, we just need to change the DNS records for https://publicdomainmap.org to point to GitHub's servers (see [how-to](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site)).

**Comment by jimmyrocks** [comment]
I've moved the main page (www) over to github pages and no subdomain (https://publicdomainmap.org/) is set to forward to www. The rest of the site doesn't work anymore, but this if fixed!
